In [1]:
#数组的创建

In [72]:
import numpy as np
data = np.random.randn(2, 3)
data

array([[-0.59471353,  0.68152192,  1.0436849 ],
       [ 0.48876267, -0.60270897, -0.2866343 ]])

In [3]:
data + data

array([[-0.57584331, -1.39077243,  1.76140704],
       [-0.17710151,  1.25203779, -0.03949288]])

In [4]:
data ** 10

array([[3.91510373e-06, 2.64399592e-02, 2.80735490e-01],
       [2.96430361e-11, 9.24430802e-03, 9.01338015e-18]])

In [5]:
data1= [6, 22, 8.9, 21]
arr1 = np.array(data1)

In [6]:
arr1.dtype

dtype('float64')

In [7]:
arr1.shape

(4,)

In [8]:
data2 = [(2,3,3,1), (3,4,5,6)]
arr2 = np.array(data2)
arr2.shape

(2, 4)

In [9]:
arr2.dtype

dtype('int32')

In [10]:
np.zeros_like(arr2)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [11]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [14]:
arr2.astype(np.string_)

array([[b'2', b'3', b'3', b'1'],
       [b'3', b'4', b'5', b'6']], dtype='|S11')

In [28]:
a_slice = arr[5:8]
a_slice[:] = [55, 33,44]
arr

array([ 0,  1,  2,  3,  4, 55, 33, 44,  8,  9])

In [36]:
#索引和切片
arr = np.arange(10)
a = arr[5]
a += 55
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr2 = np.arange(12).reshape((3,4))
a = arr2[1]
a[:2] = 44
arr2

array([[ 0,  1,  2,  3],
       [44, 44,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
arr3 = np.arange(36).reshape((3,3,4))
arr3[1][1][1]
arr3[1, ]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [69]:
a = arr3[0]
a[1] = 88
arr3

array([[[ 0,  1,  2,  3],
        [88, 88, 88, 88],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [71]:
arr3[1:, 0, 2:]

array([[14, 15],
       [26, 27]])

In [ ]:
#布尔型数组

In [88]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Book", "Nike", "Soo"])
data = np.random.randn(2,7,4)
data1 = np.random.randn(7)
data

array([[[ 0.8629049 ,  0.94884811, -1.02716079,  1.27387569],
        [-1.05000221,  0.52991244,  1.37102317,  0.72267666],
        [ 1.64723246, -1.33386525, -0.30978588, -0.23711105],
        [-1.51968096,  0.31842643,  0.05301127,  0.176248  ],
        [ 1.04280175,  0.11963412, -0.81072267,  0.07628697],
        [ 1.33906493,  0.0661196 ,  0.14064057, -0.34286039],
        [ 0.51315271, -2.44263222,  0.22629247,  1.6447065 ]],

       [[ 0.39143861, -1.23194732, -0.47081383,  1.41199298],
        [ 0.05162978, -0.87164755, -1.04990355,  0.9014203 ],
        [ 1.18051652, -0.84458869, -0.50408605, -0.01161262],
        [-0.78291863,  1.97730334, -0.30270521, -0.45173944],
        [ 1.0082998 ,  0.77337088, -0.69437647,  0.68029093],
        [ 0.93246802,  0.91084133,  0.20705285, -1.03782403],
        [ 1.04306488,  0.95447221,  0.9493524 ,  0.35725108]]])

In [89]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [94]:
data[:2,names=="Bob", :2]

array([[[ 0.8629049 ,  0.94884811],
        [-1.51968096,  0.31842643]],

       [[ 0.39143861, -1.23194732],
        [-0.78291863,  1.97730334]]])

In [84]:
data1[names=="Bob"]

array([1.43454409, 1.81834493])