In [1]:
#数组的创建
import numpy as np
data = np.random.randn(2, 3)
data

array([[ 2.13320894, -1.15607049,  0.34759762],
       [-0.92147232, -0.2062849 , -0.50560036]])

In [3]:
data + data

array([[-0.57584331, -1.39077243,  1.76140704],
       [-0.17710151,  1.25203779, -0.03949288]])

In [4]:
data ** 10

array([[3.91510373e-06, 2.64399592e-02, 2.80735490e-01],
       [2.96430361e-11, 9.24430802e-03, 9.01338015e-18]])

In [5]:
data1= [6, 22, 8.9, 21]
arr1 = np.array(data1)

In [6]:
arr1.dtype

dtype('float64')

In [7]:
arr1.shape

(4,)

In [8]:
data2 = [(2,3,3,1), (3,4,5,6)]
arr2 = np.array(data2)
arr2.shape

(2, 4)

In [9]:
arr2.dtype

dtype('int32')

In [10]:
np.zeros_like(arr2)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [11]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [14]:
arr2.astype(np.string_)

array([[b'2', b'3', b'3', b'1'],
       [b'3', b'4', b'5', b'6']], dtype='|S11')

In [28]:
a_slice = arr[5:8]
a_slice[:] = [55, 33,44]
arr

array([ 0,  1,  2,  3,  4, 55, 33, 44,  8,  9])

In [36]:
#索引和切片
arr = np.arange(10)
a = arr[5]
a += 55
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr2 = np.arange(12).reshape((3,4))
a = arr2[1]
a[:2] = 44
arr2

array([[ 0,  1,  2,  3],
       [44, 44,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
arr3 = np.arange(36).reshape((3,3,4))
arr3[1][1][1]
arr3[1, ]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [69]:
a = arr3[0]
a[1] = 88
arr3

array([[[ 0,  1,  2,  3],
        [88, 88, 88, 88],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [71]:
arr3[1:, 0, 2:]

array([[14, 15],
       [26, 27]])

In [20]:
#布尔型数组
names = np.array(["Bob", "Joe", "Will", "Bob", "Book", "Nike", "Soo"])
data = np.random.randn(2,7,4)
data1 = np.random.randn(7)
data

array([[[ 0.51170953, -0.07712556, -1.05745012, -0.27704819],
        [ 2.89898581,  0.42801871, -1.68907409,  1.11265974],
        [-1.29311264,  0.33478899,  1.0168691 , -0.44062838],
        [ 0.35222041, -0.82903384, -1.05370365,  1.1640279 ],
        [ 2.40198157,  1.49469044, -0.00859507, -0.02253127],
        [ 0.07476421,  0.19101853, -1.51826607,  0.36327673],
        [ 1.48843744, -0.49648609,  0.57688018, -0.65962479]],

       [[-0.47589549,  0.81824049, -0.88141369,  1.06847951],
        [-0.76955744, -0.07380541,  2.05880682, -0.27106064],
        [ 1.43294476, -0.80988376, -1.3105042 ,  0.8869198 ],
        [ 1.07555243, -1.68560112, -0.85838777,  0.68469225],
        [-0.41066734, -1.46305902,  0.22128381,  2.21895641],
        [-1.02927576, -0.68955424, -0.97340158,  0.15289224],
        [-0.374005  , -0.73003016, -0.46097384, -1.0758764 ]]])

In [14]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [15]:
data[:2,names=="Bob", :2]

array([[[-0.74886973, -0.26382799],
        [ 1.13467454, -2.13791891]],

       [[-0.53810774,  0.63256229],
        [-1.37625242,  0.29550152]]])

In [5]:
data1[names=="Bob"]

array([0.2036945 , 1.51365787])

In [16]:
data[:2,(names=="Bob") | (names=="Nike"), :2]

array([[[-0.74886973, -0.26382799],
        [ 1.13467454, -2.13791891],
        [ 0.52155787,  0.72082715]],

       [[-0.53810774,  0.63256229],
        [-1.37625242,  0.29550152],
        [ 0.37079361,  0.40664754]]])

In [18]:
data[data<0] = 0
data

array([[[0.        , 0.        , 0.        , 1.14330903],
        [0.        , 0.        , 0.03067748, 0.9023098 ],
        [0.21152644, 1.00655233, 0.69990655, 0.        ],
        [1.13467454, 0.        , 0.        , 0.        ],
        [0.        , 0.17238972, 0.        , 0.20720611],
        [0.52155787, 0.72082715, 1.23847847, 0.        ],
        [0.76713014, 0.60018125, 0.        , 0.        ]],

       [[0.        , 0.63256229, 1.02740723, 0.40743892],
        [0.        , 0.        , 0.        , 0.        ],
        [0.19982142, 0.06434617, 0.        , 0.54701428],
        [0.        , 0.29550152, 0.39299611, 0.32294192],
        [0.        , 0.08113614, 0.29084415, 0.79259225],
        [0.37079361, 0.40664754, 0.        , 0.44646305],
        [0.        , 0.58247464, 0.        , 0.7231912 ]]])

In [34]:
#花式索引
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i

In [35]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [51]:
arr[:][:,[0,3,1,2]]

array([[ 0,  3,  1,  2],
       [ 4,  7,  5,  6],
       [ 8, 11,  9, 10],
       [12, 15, 13, 14],
       [16, 19, 17, 18],
       [20, 23, 21, 22],
       [24, 27, 25, 26],
       [28, 31, 29, 30]])

In [43]:
arr = np.arange(32).reshape((8,4))
arr[[1,5,7,2], [0,3,2,1]]

array([ 4, 23, 30,  9])

In [32]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [54]:
#转置
arr = np.arange(32).reshape((8,4))
arr.T
np.transpose(arr)

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [53]:
np.dot(arr.T, arr)

array([[2240, 2352, 2464, 2576],
       [2352, 2472, 2592, 2712],
       [2464, 2592, 2720, 2848],
       [2576, 2712, 2848, 2984]])